swagger: "2.0"
info:
  description: REST API with CRUD 
  version: "1.0.0"
  title: Full Stack Application 
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /people:
    get:
      operationId: people.read_all
      tags:
        - People
      summary: Read the entire set of people, sorted by last name
      description: Read the entire set of people, sorted by last name
      responses:
        200:
          description: Successfully read people set operation
          schema:
            type: array
            items:
              properties:
                person_id:
                  type: integer
                  description: Id of the person
                fname:
                  type: string
                  description: First name of the person
                lname:
                  type: string
                  description: Last name of the person
                timestamp:
                  type: string
                  description: Create/Update timestamp of the person
                notes:
                  type: array
                  items:
                    properties:
                      person_id:
                        type: integer
                        description: Id of person this note is associated with
                      note_id:
                        type: integer
                        description: Id of this note
                      content:
                        type: string
                        description: content of this note
                      timestamp:
                        type: string
                        description: Create/Update timestamp of this note

    post:
      operationId: people.create
      tags:
        - People
      summary: Create a person
      description: Create a new person
      parameters:
        - name: person
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of person to create
              lname:
                type: string
                description: Last name of person to create
      responses:
        201:
          description: Successfully created person
          schema:
            properties:
              person_id:
                type: integer
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record

  /people/{person_id}:
    get:
      operationId: people.read_one
      tags:
        - People
      summary: Read one person
      description: Read one person
      parameters:
        - name: person_id
          in: path
          description: Id of the person to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read person from people data operation
          schema:
            type: object
            properties:
              person_id:
                type: string
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record
              notes:
                type: array
                items:
                  properties:
                    person_id:
                      type: integer
                      description: Id of person this note is associated with
                    note_id:
                      type: integer
                      description: Id of this note
                    content:
                      type: string
                      description: content of this note
                    timestamp:
                      type: string
                      description: Create/Update timestamp of this note

    put:
      operationId: people.update
      tags:
        - People
      summary: Update a person
      description: Update a person
      parameters:
        - name: person_id
          in: path
          description: Id the person to update
          type: integer
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
      responses:
        200:
          description: Successfully updated person
          schema:
            properties:
              person_id:
                type: integer
                description: Id of the person in the database
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record

    delete:
      operationId: people.delete
      tags:
        - People
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - name: person_id
          in: path
          type: integer
          description: Id of the person to delete
          required: true
      responses:
        200:
          description: Successfully deleted a person

  /address:
    get:
      operationId: addresses.read_all
      tags:
        - Address 
      summary: Read the entire set of notes for all people, sorted by timestamp
      description: Read the entire set of notes for all people, sorted by timestamp
      responses:
        200:
          description: Successfully read notes for all people operation
          schema:
            type: array
            items:
              properties:
                note_id:
                  type: integer
                  description: Id of the note
                content:
                  type: string
                  description: Content of the note
                timestamp:
                  type: string
                  description: Create/Update timestamp of the note
                person:
                  type: object
                  properties:
                    person_id:
                      type: integer
                      description: Id of associated person
                    fname:
                      type: string
                      description: Frist name of associated person
                    lname:
                      type: string
                      description: Last name of associated person
                    timestamp:
                      type: string
                      description: Create/Update timestamp of associated person

  /address/{person_id}/address/{address_id}:
    get:
      operationId: addresses.read_one
      tags:
        - Address 
      summary: Read a particular address associated with a person
      description: Read a particular address associated with a person
      parameters:
        - name: person_id
          in: path
          description: Id of person associated with address 
          type: integer
          required: True
        - name: address_id
          in: path
          description: Id of address 
          type: integer
          required: True
      responses:
        200:
          description: Successfully read an address for a person
          schema:
            type: object
            properties:
              note_id:
                type: integer
                description: Id of the address 
              person_id:
                type: integer
                description: Id of the person address associated with
              content:
                type: string
                description: Text content of the address 
              timestamp:
                type: string
                description: Creation/Update timestamp of the address record

    delete:
      operationId: addresses.delete
      tags:
        - Address 
      summary: Delete an address associated with a person
      description: Delete an address  associated with a person
      parameters:
        - name: person_id
          in: path
          description: Id of person associated with address 
          type: integer
          required: True
        - name: address_id
          in: path
          description: Id of Address 
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted an address

    put:
      operationId: addresses.update
      tags:
        - Address
      summary: Update an address associated with a person
      description: Update an address associated with a person
      parameters:
        - name: person_id
          in: path
          description: Id of person associated with address
          type: integer
          required: True
        - name: address_id
          in: path
          description: Id of Address
          type: integer
          required: True
        - name: address
          in: body
          description: Address details
          required: True
          schema:
            type: object
            properties:
              addr_type:
                type: string
              addr_line1:
                type: string
                description: address line 1
              addr_line2:
                type: string
                description: address line 2
              addr_line3:
                type: string
                description: address line 3
              addr_line4:
                type: string
                description: address line 4
              country_code:
                type: string
                description: country code
              zip_code:
                type: integer
                description: zip code
              state:
                type: string
                description: state
              city:
                type: string
                description: city
      responses:
        200:
          description: Successfully updated an address
          


  /people/{person_id}/address:
    post:
      operationId: addresses.create
      tags:
        - Address 
      summary: Create an address associated with a person
      description: Create anaddress associated with a person
      parameters:
        - name: person_id
          in: path
          description: Address to create
          type: integer
          required: True
        - name: address
          in: body
          description: Address details
          required: True
          schema:
            type: object
            properties:
              addr_type:
                type: string
                description: type of address
              addr_line1:
                type: string
                description: address line 1                
              addr_line2:
                type: string
                description: address line 2 
              addr_line3:
                type: string
                description: address line 3 
              addr_line4:
                type: string
                description: address line 4 
              country_code:
                type: string
                description: country code
              zip_code:
                type: integer
                description: zip code
              state:
                type: string
                description: state 
              city:
                type: string
                description: city
      responses:
        200:
          description: Successfully created an address 
